spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: product-manager
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-manager/**
          filters:
            - RewritePath=/product-manager/(?<segment>.*), /$\{segment}
        - id: user-manager
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-manager/**
          filters:
            - RewritePath=/user-manager/(?<segment>.*), /$\{segment}
        - id: order-manager
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-manager/**
          filters:
            - RewritePath=/order-manager/(?<segment>.*), /$\{segment}
        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/main
          filters:
            - SetPath=/
        - id: eureka-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

server:
  port: 8080

